name = "franklincli"

[install]
completion = true
quiet = false
optimize = 2

[sysimg]
path = "deps/lib"
incremental = false
filter_stdlibs = true
cpu_target = "x86-64"

[download]
host = "github.com"
user = "Roger-luo"
repo = "FranklinCLI.jl"
